(defun parte-reala (c)
    (if (complexp c)
        (realpart c)
        (format t "Nu e complex")
    )
)

(defun parte-imaginara (c)
    (if (complexp c)
        (imagpart c)
        (format t "Nu e complex")
    )
)
(defun afisare (c)
    (if (complexp c)
        (format t "~d = ~d + ~d*i" c (parte-reala c) (parte-imaginara c))
        (format t "Nu e complex")
    )
)

(defun egalitate (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (equalp c1 c2)
        (format t "Nu sunt complexe")
    )
)

(defun adunare (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (+ c1 c2)
        (format t "Nu sunt complexe")
    )
)

(defun scadere (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (- c1 c2)
        (format t "Nu sunt complexe")
    )
)

(defun inmultire (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (* c1 c2)
        (format t "Nu sunt complexe")
    )
)

(defun impartire (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (/ c1 c2)
        (format t "Nu sunt complexe")
    )
)